version: '{build}'
image: Visual Studio 2017
configuration:
- Debug
- Release
before_build:
- git submodule update --init --recursive
- nuget restore TLM/TMPE.sln
skip_tags: true
build:
  project: TLM/TMPE.sln
  verbosity: minimal